export const KEY = 'TODO';
export const COLORS = {
    green: 'green',
    red: 'red',
    blue: 'blue',
    orange: 'orange',
    purple: 'purple',
};
export const STATUS = {
    active: 'active',
    completed: 'completed',
    all: 'all',
};
export const TODOGETDATA_ACTION = 'TODO/GETDATA';
export const TODOGETDATA_REQUEST = 'TODO/GETDATA_REQUEST';
export const TODOGETDATA_SUCCESS = 'TODO/GETDATA_SUCCESS';
export const TODOGETDATA_ERROR = 'TODO/GETDATA_ERROR';

export const TODOADDITEM_ACTION = 'TODO/ADDITEM';
export const TODOADDITEM_REQUEST = 'TODO/ADDITEM_REQUEST';
export const TODOADDITEM_SUCCESS = 'TODO/ADDITEM_SUCCESS';
export const TODOADDITEM_ERROR = 'TODO/ADDITEM_ERROR';

export const TODOCOMPLETEITEM_ACTION = 'TODO/COMPLETEITEM';
export const TODOCOMPLETEITEM_REQUEST = 'TODO/COMPLETEITEM_REQUEST';
export const TODOCOMPLETEITEM_SUCCESS = 'TODO/COMPLETEITEM_SUCCESS';
export const TODOCOMPLETEITEM_ERROR = 'TODO/COMPLETEITEM_ERROR';

export const TODODELETE_ACTION = 'TODO/DELETE';
export const TODODELETE_REQUEST = 'TODO/DELETE_REQUEST';
export const TODODELETE_SUCCESS = 'TODO/DELETE_SUCCESS';
export const TODODELETE_ERROR = 'TODO/DELETE_ERROR';

export const TODOUPDATE_ACTION = 'TODO/UPDATE';
export const TODOUPDATE_REQUEST = 'TODO/UPDATE_REQUEST';
export const TODOUPDATE_SUCCESS = 'TODO/UPDATE_SUCCESS';
export const TODOUPDATE_ERROR = 'TODO/UPDATE_ERROR';

export const TODOCOMPLETEALL_ACTION = 'TODO/COMPLETEALL';
export const TODOCOMPLETEALL_REQUEST = 'TODO/COMPLETEALL_REQUEST';
export const TODOCOMPLETEALL_SUCCESS = 'TODO/COMPLETEALL_SUCCESS';
export const TODOCOMPLETEALL_ERROR = 'TODO/COMPLETEALL_ERROR';

export const TODOCLEARCOMPLETEALL_ACTION = 'TODO/CLEARCOMPLETEALL';
export const TODOCLEARCOMPLETEALL_REQUEST = 'TODO/CLEARCOMPLETEALL_REQUEST';
export const TODOCLEARCOMPLETEALL_SUCCESS = 'TODO/CLEARCOMPLETEALL_SUCCESS';
export const TODOCLEARCOMPLETEALL_ERROR = 'TODO/COMPLETEALL_ERROR';

export const FILTERADDSTATUS = 'FILTERADDSTATUS';
export const FILTERADDCOLOR = 'FILTERADDCOLOR';
